import Happier from '../../assets/images/Happier than Ever.png'
import Evermore from '../../assets/images/Evermore.png'
import This from '../../assets/images/This is Why.png'
import Blue from '../../assets/images/Blue banisters.png'
import Women from '../../assets/images/Haim.png'
import Idler from '../../assets/images/The Idler.png'
import If from '../../assets/images/If i cant have love.png'
import Loneliest from '../../assets/images/The Loneliest Time.png'
import Bewithced from '../../assets/images/Bewithced.png'
import Brand from '..//../assets/images/Brand new Eyes.png'
import Garden from '..//../assets/images/Garden.png'
import Melodrama from '..//../assets/images/Melodrama.png'
import Titanic from '..//../assets/images/Titanic.png'
import Weekend from '..//../assets/images/Blue weekend.png'
import Norman from '..//../assets/images/Norman.png'
import Puberty from '..//../assets/images/Puberty 2.png'
import Zeros from '..//../assets/images/Zeros.png'
import Bury from '..//../assets/images/Bury Me.png'
import Pure from '../../assets/images/Lorde (1).png'
import Ends from '../../assets/images/Labrinth.png'
import Superache from '../../assets/images/Conan.png'
import Did from '../../assets/images/Did You Know.png'
import Blood from '../../assets/images/Finneas.png'
import Singular from '../../assets/images/Sabrinão.png'
import Punisher from '../../assets/images/Punisher.png'
import Fountain from '../../assets/images/Fountain.png'
import Ctrl from '../../assets/images/Ctrl.png'
import Janelle from '../../assets/images/Janelle.png'
import Raven from '../../assets/images/Raven.png'
import Bb from '../../assets/images/Tinashe.png'
import Sos from '../../assets/images/SOS.png'
import Red from '../../assets/images/Kali.png'
import Born from '../../assets/images/Born To Die.png'
import Ultraviolence from '../../assets/images/Ultraviolence.png'
import Honeymoon from '../../assets/images/Honeymoon.png'
import Lust from '../../assets/images/Lust For Life.png'
import Chemtrails from '../../assets/images/Chemtrails.png'
import Daddys from '../../assets/images/Daddys home.png'
import How from '../../assets/images/How big (1).png'
import Laurel from '../../assets/images/Laurel Hell.png'
import Look from '../../assets/images/Look alive.png'
import Nightmare from '../../assets/images/Nightmare.png'
import Wiped from '../../assets/images/Wiped out.png'

export const slides1 = [Happier, Evermore, This, Women, Idler, If, Loneliest, Bewithced, Brand, Garden, Melodrama, Titanic, Weekend, Norman, Zeros, Bury, Pure, Ends, Superache, Did, Blood, Singular, Punisher, Fountain, Ctrl, Janelle, Raven, Bb, Sos, Red, Born, Ultraviolence, Honeymoon, Lust, Chemtrails, Did, How, Laurel, Look, Nightmare, Wiped, Puberty, If, Blue, Daddys];
export const slides2 = [Brand, Garden, Melodrama, Titanic, Weekend, Norman, Puberty, Zeros, Bury];
export const slides3 = [Pure, Ends, Superache, Did, Blood, Singular, Punisher];
export const slides4 = [Fountain, Ctrl, Janelle, Raven, Bb, Sos, Red];
export const slides5 = [Born, Ultraviolence, Honeymoon, Lust, Norman, Chemtrails, Blue, Did];
export const slides6 = [Daddys, How, Laurel, Look, Nightmare, If, Wiped];